baseURL: ""
languageCode: en-us
title: My New Hugo Site
theme: PaperMod

params:
  homeInfoParams:
    Title: 'Hello!'
    Content: Welcome to my blog. Here you'll find a lot of cool information about a lot of cool stuff.
  socialIcons:
    - name: facebook
      url: 'https://facebook.com/'
    - name: twitter
      url: 'https://twitter.com'
    - name: github
      url: 'https://github.com'
  cover:
    linkFullImages: true

  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories # the text that we see
      url: /categories/
      weight: 10 # order
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30
